version: '2'
services:

  consul:
    restart: always
    ports:
      - '8300:8300'
      - '8500:8500'
      - '8400:8400'
      - '8301:8301/tcp'
      - '8301:8301/udp'
      - '8302:8302/udp'
      - '8302:8302/tcp'
      - '8600:8600'
    network_mode: "host"
    #enable data persistency for server
    #volumes:
    # - /opt/consul/data:/opt/consul/data
    environment:
      CONSULSERVER: "kvm-nom-01.pdmz.eea"
    container_name: consul-client
    image: consul:1.10.3
    #client
    command: /bin/sh -c 'consul agent -node=ci -advertise=`hostname -i` -data-dir=/opt/consul/data -node=`hostname` -join=$${CONSULSERVER}'
    #server
    #command: /bin/sh -c 'consul agent -server -ui -node=`hostname` -bootstrap-expect=1 -advertise=`hostname -i` -client=0.0.0.0 -data-dir=/opt/consul/data'

  nomad:
    image: eeacms/nomad
    restart: always
    privileged: true
    ports:
      - '4649:4649'
      - '4647:4647'
      - '4648:4648'
      - '4646:4646'
    network_mode: "host"
    depends_on: 
      - consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      #server
      #nomad agent -config=/etc/nomad.d/server.hcl
      #client
      nomad agent -config=/etc/nomad.d/client.hcl
      #dev
      #nomad agent -dev -bind 0.0.0.0 -log-level INFO
