
version: '2'
services:
  consul:
    image: consul:1.12.0
    restart: always
    ports:
      - '8300:8300'
      - '8500:8500'
      - '8400:8400'
      - '8301:8301/tcp'
      - '8301:8301/udp'
      - '8302:8302/udp'
      - '8302:8302/tcp'
      - '8600:8600'
    network_mode: "host"
    volumes:
#    - /opt/consul:/opt/consul
    - nfsvolume:/opt
    environment:
      CONSULSERVER: "dns_name_of_your_consul"
      DATADIR: "/tmp"
      ENCRYPTION_KEY: "something_very_secret_for_consul"
      DATACENTER: "dc1"
    container_name: consul
    command: /bin/sh -c 'consul agent -node=ci -datacenter=$${DATACENTER} -advertise=`hostname -i` -config-dir=/opt/consul/config/client -data-dir=$${DATADIR} -node=`host
name` -join=$${CONSULSERVER} -encrypt=$${ENCRYPTION_KEY}'

  nomad-server:
    image: eeacms/nomad:1.3.0
    container_name: nomad-server
    restart: always
    privileged: true
    #enable for server
    ports:
      - '4646:4646'
      - '4647:4647'
      - '4648:4648'
      - '4649:4649'
    network_mode: "host"
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nfsvolume:/opt
    environment:
      DATADIR: "/tmp"
      DATACENTER: "dc1"
      ENCRYPTION_KEY: "something_very_secret_for_nomad"
      BOOTSTRAP_EXPECT: 2
    command:
      /bin/sh -c 'nomad agent -config=/opt/nomad/config/server.hcl -bootstrap-expect=$${BOOTSTRAP_EXPECT} -data-dir=$${DATADIR} -dc=$${DATACENTER} -encrypt=$${ENCRYPTION_
KEY} -acl-enabled'

#for simplicity all configuration files are in a nfs share 
volumes:
  nfsvolume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=dns_name,port=2049,rw,nfsvers=4,async
      device: ":/"



